book_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   "authors#index"

  get    "/login",            to: "sessions#new",     as: :login
  delete "/logout",           to: "sessions#destroy", as: :logout
  post   "/login",            to: "sessions#create"

  post   "/users/search",     to: "users#search"
  get    "/signup",           to: "users#new",        as: :signup

  get    "/authors",          to: "authors#index",    as: :authors 
  post   "/authors",          to: "authors#create"
  get    "/authors/new",      to: "authors#new",      as: :new_author
  get    "/authors/:id/edit", to: "authors#edit",     as: :edit_author 
  get    "/authors/:id",      to: "authors#show",     as: :author
  patch  "/authors/:id",      to: "authors#update"
  put    "/authors/:id",      to: "authors#update"
  delete "/authors/:id",      to: "authors#destroy"

  resources :books
  resources :users,    only: [:index, :create, :show]
  resources :comments, only: [:create, :update, :destroy]

end

book_app/app/models/author.rb
class Author < ApplicationRecord
  has_many :books, :dependent => :destroy
  validates :email, confirmation: true,
      presence: true,
      uniqueness: true,
      format: {
        with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/,
        message: "Invalid email address"
      }
  validates :email_confirmation, presence: true
  validates :name, presence: true
end

book_app/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :comments, :dependent => :destroy
  validates :title, presence: true
  validates :author_id, presence: true
  validates :genre, presence: true
  validates :pages, numericality: {
      only_integer: true }, presence: true
end

book_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
  validates :content, presence: true
end

book_app/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments, :dependent => :destroy
  before_validation :downcase_email
  validates :email,
      presence: true,
      uniqueness: true,
      format: {
        with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/,
        message: "Invalid email address"
      }
  validates :password_confirmation, presence: true
  validates :password, confirmation: true
  validates :name, presence: true
  validates :avatar, presence: true, format: {
    with:  URI::regexp(%w(http https)),
    message: "please insert a image url"
  }

  private
  def downcase_email
    self.email = email.downcase if email.present?
  end
end

book_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def logged_in?
    @logged_in = !!current_user
  end
end

book_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :logged_in?, only: [:index, :show, :new, :update]
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.valid?
      @author.save
      redirect_to @author
    else
      flash[:author] = @author.errors.messages
      redirect_back fallback_location: new_author_path
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to @author
    else
      flash[:author] = @author.errors.messages
      redirect_back fallback_location: edit_author_path(@author)
    end
  end

  def destroy
    if @author.destroy
      redirect_to authors_path
    else
      flash[:error] = "Could not delete author."
      redirect_back
    end
  end

  private

  def author_params
    params.require(:author).permit(:name, :email, :email_confirmation)
  end

  def set_author
    @author = Author.find(params[:id])
  end
end

book_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_user
  before_action :logged_in?, only: [:index, :show, :new, :update]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    @comments = @book.comments.order(:created_at)
    @comment = @book.comments.new(:user_id => @current_user.id)
  end

  def new
    @book = Book.new
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @book.save
      redirect_to @book
    else
      puts @book.errors.messages
      flash[:book] = @book.errors.messages
      redirect_back fallback_location: new_book_path
    end
  end

  def edit
    @authors = Author.all
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      flash[:book] = @book.errors.messages
      redirect_back fallback_location: edit_book_path(@book)
    end
  end

  def destroy
    if @book.destroy
      redirect_to books_path
    else
      flash[:error] = "Could not delete book."
      redirect_back fallback_location: @book
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :genre, :author_id, :pages)
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

book_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  before_action :set_comment, only: [:update, :destroy]

  def create
    @comment = Comment.new(comment_params)
    @book = Book.find(params[:comment][:book_id])
    unless @comment.save
      flash[:comment] = @comment.errors.messages
    end
    redirect_back fallback_location: @book
  end

  def update
    unless @comment.update(comment_params)
      flash[:comment] = @comment.errors.messages
    end
    redirect_back fallback_location: @comment.book
  end

  def destroy
    @comment.destroy
    redirect_back fallback_location: @comment
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:content, :user_id, :book_id)
  end
end

book_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in?, only: [:new]

  def new
  end

  def create
	  @user = User.find_by_email(params[:session][:email].downcase)
	  if @user
      if @user.authenticate(params[:session][:password])
	       session[:user_id] = @user.id
	        redirect_to @user
      else
        flash[:user] = { :password => ["Incorrect password"] }
        redirect_to '/login'
      end
	  else
      flash[:user] = { :email => ["No user with that email"] }
	    redirect_to '/login'
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to '/login'
	end
end

book_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :index]
  before_action :logged_in?, only: [:show, :index]

  def search
    @users = User.where('LOWER(name) LIKE ?', "%#{params[:q].downcase}%").order(:name)
    render :json => {:users => @users}
  end
  def show
    @user = User.find(params[:id])
  end
  def new
   @user = User.new
  end

 def create
   @user = User.new(user_params)
   @user.avatar = "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email)}?d=identicon&f=y"
   if @user.save
     session[:user_id] = @user.id
     redirect_to @user
   else
     redirect_to '/signup'
   end
 end

 private
   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end
end

book_app/app/views/authors/edit.html.erb
<h1 class="page-title img-line second-bg">Edit Author</h1>
<%= render "shared/author_form", {author: @author} %>

book_app/app/views/authors/index.html.erb
<h1 class="page-title second-bg">Authors</h1>
<div class="info-list">
  <% @authors.each do |author| %>
    <div class="author-info info">
      <h2 class="card-title"><%= link_to(author.name, author) %></h2>
      <%= render "shared/book_list", {books: author.books} %>
    </div>
  <% end %>
</div>

book_app/app/views/authors/new.html.erb
<h1 class="page-title img-line second-bg">New Author</h1>
<%= render "shared/author_form", {author: @author} %>

book_app/app/views/authors/show.html.erb
<h1 class="page-title img-line second-bg">Author</h1>
<div class="show">
    <div class="author-info info">
        <div class="card-title">
            <h2><%= @author.name %></h2>
            <p><%= @author.email %></p>
        </div>
        <%= render "shared/book_list", {books: @author.books} %>
        <div class="card-footer">
            <p>Don't see a book?
                <%= link_to("Add one now!", new_book_path) %></p>
            <div class="footer-buttons">
                <%= link_to("✎", edit_author_path(@author), :class => "pop-button") %>
                <%= button_to("✕", @author, method: :delete, :class=>"pop-button") %>
            </div>
        </div>
    </div>
</div>

book_app/app/views/books/edit.html.erb
<h1 class="page-title img-line first-bg">Edit Book</h1>
<%= render "shared/book_form", {authors: @authors, book: @book} %>

book_app/app/views/books/index.html.erb
<h1 class="page-title first-bg">Books</h1>

<div class="info-list">
    <% @books.each do |book| %>
    <div class="book-info info">
        <h2 class="card-title"><%= link_to(book.title, book) %></h2>
        <h4><%= link_to("By: #{book.author.name}", book.author) %></h4>
    </div>
    <% end %>
</div>

book_app/app/views/books/new.html.erb
<h1 class="page-title img-line first-bg">New Book</h1>
<%= render "shared/book_form", {authors: @authors, book: @book} %>

book_app/app/views/books/show.html.erb
<h1 class="page-title img-line first-bg">Book</h1>
<div class="show">
    <div class="book-info info">
        <h2 class="card-title"><%= @book.title %></h2>
        <h4><%= link_to("By: #{@book.author.name}", @book.author) %></h4>
        <p>Genre: <%= @book.genre %></p>
        <p>Pages: <%= @book.pages %></p>
        <div class="card-footer">
            <div class="footer-buttons">
                <%= link_to("✎", edit_book_path(@book), :class => "pop-button") %>
                <%= button_to("✕", @book, method: :delete, :class=>"pop-button") %>
            </div>
        </div>
    </div>
    <div class="info">
      <h2 class="card-title">Comments</h2>
      <div class="comments">
        <div class="new-comment">
          <img src=<%= @current_user.avatar %> alt="">
          <%= form_for(@comment, :html => {:class => "form comment-info"}) do |f| %>
          <h3><%= @current_user.name %></h3>
          <div class="input-group">
            <%= f.text_area :content, :placeholder => "Comment" %>
            <%= render "shared/input_errors", {errors: flash["comment"] ? flash["comment"]["content"] : []} %>
          </div>
          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :book_id, :value => @book.id%>
          <%= f.submit %>
          <% end %>
        </div>
        <div class="comments-container">
          <% @comments.each do |comment| %>
            <div class="comment">
              <img src=<%= comment.user.avatar %> alt="">
              <div class="comment-info" >
                <div class="title">
                  <h3>
                    <%= comment.user.name %>
                    <span class="comment-date">
                      <%= comment.created_at.strftime("%m/%d/%Y %I:%M%p") %>
                    </span>
                  </h3>
                  <% if comment.user.id == @current_user.id %>
                    <div class="footer-buttons">
                        <button class="pop-button edit-comment" data-id=<%= comment.id %>>✎</button>
                        <%= button_to("✕", comment, method: :delete, :class=>"pop-button") %>
                    </div>
                  <% end %>
                </div>
                <p id=<%= "#{comment.id}-info" %>><%= comment.content %></p>
                <% if comment.user.id == @current_user.id %>
                  <%= form_for(comment, :html => {:class => "form comment-info edit-comment", :id=> "#{comment.id}-form"}) do |f| %>
                    <div class="input-group">
                      <%= f.text_area :content, :placeholder => "Comment" %>
                      <%= render "shared/input_errors", {errors: flash["comment"] ? flash["comment"]["content"] : []} %>
                    </div>
                    <%= f.hidden_field :user_id %>
                    <%= f.hidden_field :book_id, :value => @book.id%>
                    <%= f.submit %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer">
    </div>
</div>

book_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Club</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <h1>Book Club</h1>
      <% if @logged_in %>
        <div class="nav-links">
          <%= link_to("Authors", authors_path) %>
          <%= link_to("Books", books_path) %>
          <%= link_to("New Author", new_author_path) %>
          <%= link_to("New Book", new_book_path) %>
          <%= link_to("Users", users_path) %>
          <%= link_to("Profile", current_user) %>
          <%= link_to("Logout", logout_path, :method => "delete") %>
        </div>
      <% else %>
        <div class="nav-links">
          <%= link_to("Authors", authors_path) %>
          <%= link_to("New Author", new_author_path) %>
          <%= link_to("Log In", login_path) %>
          <%= link_to("Sign Up", signup_path) %>
        </div>
      <% end %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

book_app/app/views/shared/_author_form.html.erb
<%= form_for(author, :html => {:class => "form"}) do |f| %>
  <div class="input-group"> 
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= render "shared/input_errors", {errors: flash["author"] ? flash["author"]["name"] : []} %>
  </div>
  <div class="input-group">
    <%= f.label :email %>
    <%= f.email_field :email %>
      <%= render "shared/input_errors", {errors: flash["author"] ? flash["author"]["email"] : []} %>
  </div>
  <div class="input-group">
    <%= f.label :email_confirmation %>
    <%= f.email_field :email_confirmation, :value => author.email %>
      <%= render "shared/input_errors", {errors: flash["author"] ? flash["author"]["email_confirmation"] : []} %>
  </div>
  <%= f.submit %>
<% end %>

book_app/app/views/shared/_book_form.html.erb
<%= form_for(book, :html => {:class => "form"}) do |f| %>
  <div class="input-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= render "shared/input_errors", {errors: flash["book"] ? flash["book"]["title"] : []} %>
  </div>
  <div class="input-group">
      <%= f.label :author %>
      <%= f.select(:author_id) do %>
      <% @authors.each do |author| %>
      <%= content_tag(:option, author.name, value: author.id) %>
      <% end %>
      <% end %>
      <%= render "shared/input_errors", {errors: flash["book"] ? flash["book"]["author_id"] : []} %>
  </div>
  <div class="input-group">
      <%= f.label :genre %>
      <%= f.text_field :genre %>
      <%= render "shared/input_errors", {errors: flash["book"] ? flash["book"]["genre"] : []} %>
  </div>
  <div class="input-group">
      <%= f.label :pages %>
      <%= f.number_field :pages %>
      <%= render "shared/input_errors", {errors: flash["book"] ? flash["book"]["pages"] : []} %>
  </div>

  <p>Don't See the author you want? <%= link_to("Make a new one.", new_author_path) %></p>

  <%= f.submit %>
<% end %>

book_app/app/views/shared/_book_list.erb
<ul class="book-list">
  <h5>Books</h5>
  <% books.each do |book| %>
    <li><%= link_to(book.title, book) %></li>
  <% end %>
</ul>

book_app/app/views/shared/_input_errors.html.erb
<% if errors && errors.size > 0 %>
  <ul class="input-errors">
    <% errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

book_app/app/views/users/index.html.erb
<div class="page-title third-bg">
  <h1>Users</h1>
  <div class="info search-info">
    <%= form_tag("/users/search", :remote=>true, :class => "search") do %>
      <%= text_field_tag(:q, '', :placeholder => "Search") %>
      <%= submit_tag("➔", :id => "submit", :class => "pop-button") %>
    <% end %>
  </div>
</div>

<div class="show">
  <div class="info results">

  </div>
</div>

book_app/app/views/users/new.html.erb
<h1 class="page-title img-line third-bg">Sign Up</h1>

<%= form_for(@user, :html => {:class => "form"}) do |f| %>
  <div class="input-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= render "shared/input_errors", {errors: flash["user"] ? flash["user"]["name"] : []} %>
  </div>

  <div class="input-group">
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= render "shared/input_errors", {errors: flash["user"] ? flash["user"]["email"] : []} %>
  </div>

  <div class="input-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= render "shared/input_errors", {errors: flash["user"] ? flash["user"]["password"] : []} %>
  </div>

  <div class="input-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= render "shared/input_errors", {errors: flash["user"] ? flash["user"]["password_confirmation"] : []} %>
  </div>

  <%= f.submit %>
<% end %>

book_app/app/views/users/show.html.erb
<h1 class="page-title img-line third-bg">User</h1>
<div class="show">
  <div class="info">
    <h2 class="card-title"><%= @user.name %></h2>
    <img src=<%= @user.avatar %> class="full-avatar">
    <p>Email: <%= @user.email %></p>
  </div>
</div>